### ISSUE TITLE
Suggested edits page: Wrong article is being opened when prev and next is used

### ISSUE THREAD

**Issue by reetssydney** [reetssydney/prototypes#8]
On the suggested edits page, when the next and previous arrow buttons are used (or when the cards are swiped to navigated through articles), the wrong article is opened on selecting to Edit.   

https://user-images.githubusercontent.com/7241063/129426436-dbea59a1-f8d1-401d-82da-028579ceb3fc.mp4

Perhaps something is broken with the `handleTraverseSuggestions` function?

**Comment by mewoph** [comment]
Fix: https://github.com/reetssydney/prototypes/pull/9
